//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budjet
    {
        public int ID_Budget { get; set; }
        public double Budget_Sum { get; set; }
        public Nullable<double> Sale_Markup { get; set; }
        public Nullable<double> Emp_Sale_Bonus { get; set; }
    }
}
