//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit_Repayment
    {
        public int ID_Repayment { get; set; }
        public int FK_Credit { get; set; }
        public System.DateTime Date_of_Repayment { get; set; }
        public Nullable<double> Fair_Sum { get; set; }
        public Nullable<double> Sum_of_Repayment { get; set; }
    
        public virtual Credit_Info Credit_Info { get; set; }
    }
}
