//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacture
    {
        public int ID_Manufacture { get; set; }
        public int FK_Production { get; set; }
        public double Total_Amount { get; set; }
        public System.DateTime Date { get; set; }
        public int FK_Employer { get; set; }
    
        public virtual Employers Employers { get; set; }
        public virtual Finished_Production Finished_Production { get; set; }
    }
}
